### ISSUE TITLE
Support different clip-paths on different elements

### ISSUE THREAD

**Issue by hagabaka** [andrusieczko/clip-path-polygon#1]
If `clipPath()` is called on multiple elements with different polygons:

```
$('#element1').clipPath([[0,1], [0,2], [1,1]]);
$('#element2').clipPath([[0,3], [0,4], [3,3],[3,4]]);
```

The plugin will only create one svg clipPath containing the second specified path.

The different clip paths appear to still work for Chrome, maybe because Chrome uses the -webkit-clip-path version in addition. although they are shown as overridden in the inspector. On Firefox the elements all use the last specified clip path. 

It would be nice if it could create additional clipPath elements for each unique clip path, generating unique ids for them, and returning the ids to allow the user to remove specific paths later.

**Comment by andrusieczko** [comment]
Thanks for that @hagabaka!

I'm sorry it took so long, it's fixed now.
