### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by Jagadeesh9** [andrusieczko/clip-path-polygon#10]
Hi,

The application is configured with waffle windows authentication framework and deployed into  Web sphere 8.5 server, its working in an Local machine. but when the same has been moved to an environment where IIS is there interacting with websphere using Websphere plugin causing Authentication issues and displaying  a windows authentication pop message, the entered username & password also not accepting.

can you please suggest if any settings need to be verified.?

Regards,
Jagadeesh

**Comment by andrusieczko** [comment]
Hi Jagadeesh,

I'm sorry for a late response, I was unavailable yesterday.

I have never used neither IIS nor Websphere. Though the library should be agnostic to the system you are using.

How do you try to download the library? Is it through `npm`? Manual download?

This is a configuration problem on your side, please read about how to use `npm` modules or github repositories (read access) with your setup.

Also, please let me know if I can close the issue.

Cheers,
Karol

**Comment by Jagadeesh9** [comment]
Hi Karol,

Step1) i have the Jar files guava-13.0.1.jar , jna-3.5.0.jar , platform-3.5.0.jar , slf4j-api-1.7.2.jar , waffle-jna.jar added in lib folder.


Step2)and web.xml have the below configurations
<filter>
              <filter-name>SecurityFilter</filter-name>
              <filter-class>waffle.servlet.NegotiateSecurityFilter</filter-class>


              <init-param>
                     <param-name>principalFormat</param-name>
                     <param-value>fqn</param-value>
              </init-param>
              <init-param>
                     <param-name>roleFormat</param-name>
                     <param-value>both</param-value>
              </init-param>
              <init-param>
                     <param-name>allowGuestLogin</param-name>
                     <param-value>true</param-value>
              </init-param>
              <init-param>
                     <param-name>waffle.servlet.spi.NegotiateSecurityFilterProvider/protocols</param-name>
                     <param-value>
                           Negotiate
                           NTLM</param-value>
              </init-param>
       </filter>

       <filter-mapping>
              <filter-name>SecurityFilter</filter-name>
              <url-pattern>/*</url-pattern>
       </filter-mapping>


Step3)request.getUserPrincipal().getName(). --> getting domainuserid

The setup is working fine when I access application using Server name and port # in my Local machine where we are not using any IIS and Websphere plugins.

but if we hit the application URL without port throwing windows authentication 401 error.

regards,
Jagadeesh

**Comment by andrusieczko** [comment]
Hi Jagadeesh,

In the code you shared, I don't see any references to my library. Hence I can't even suspect how are you using it.

Cheers,
Karol
