### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by VitoFamiglietti** [andrusieczko/clip-path-polygon#12]
Can you make the Bower's packgage for this? (Sorry i've added this into a pull request for mistake)

**Comment by andrusieczko** [comment]
Hey Vito,

I'm so sorry, I didn't have time during the weekend.

I'll try to do it today.

Cheers,
Karol

**Comment by andrusieczko** [comment]
Hi Vito,

Please check if it works for you now.

Thank you again for using the library.

Regards,
Karol

**Comment by VitoFamiglietti** [comment]
Yes, it worked well! Thank you!!!!

**Comment by andrusieczko** [comment]
You're welcome :)
