### ISSUE TITLE
Value point with percentage and px

### ISSUE THREAD

**Issue by gilangpramudya** [andrusieczko/clip-path-polygon#16]
Hi, Mate

I like your plugin, but i have a question. I'm in case with value points, this is my value (0 60px,100% 0,100% 100%,0 100%); i'm use pixel because need accurate size on polygon but i'm use percentage too.
So how to put point in your plugin?

Thanks

**Comment by andrusieczko** [comment]
Hi,

I'm sorry for not responding, I've been traveling.

That's a valid point, I'll try to look at your issue this week. I'll try to alter the library the that accepts mixed values.

Not sure if Firefox likes that though. I'll keep you updated.

Thanks for this issue,
Karol

**Comment by andrusieczko** [comment]
Hi,

So I checked the browser support and unfortunately,Firefox's Gecko engine still doesn't support this...
Here's the thread: https://bugzilla.mozilla.org/show_bug.cgi?id=1075457

So Chrome and any _webkit_ based browsers support `clip-path` as a basic style (in CSS). Gecko engines need SVG `clip-path` definition.

In SVG `clip-path`, there are only two types of units you can use: *userSpaceOnUse* and * objectBoundingBox*.
Long story short,  *userSpaceOnUse* is used when you pass the absolute values and * objectBoundingBox* requires normalized values between 0 and 1, so it's handy when dealing with percents.

Unfortunately, SVG doesn't support mixing the units, so it is technically impossible to make it happen.

Thus, I'm not sure if adding this option won't be confusing (as it'd work only in _webkit_ browsers).

I'd like to hear your opinion on this.

Cheers,
Karol
