### ISSUE TITLE
typeof syntax error

### ISSUE THREAD

**Issue by hongaar** [andrusieczko/clip-path-polygon#17]
Syntax of `typeof` is wrong here:

https://github.com/andrusieczko/clip-path-polygon/blob/master/js/clip-path-polygon.js#L115-L116

Should be changed to:

```js
this.isForWebkit = (options && typeof options.isForWebkit !== "undefined") ? options.isForWebkit : this.isForWebkit;
this.isForSvg = (options && typeof options.isForSvg !== "undefined") ? options.isForSvg : this.isForSvg;
```

**Comment by andrusieczko** [comment]
Hi @hongaar,

Oh you're right!

Apparently, the code still works as expected in most of the cases :) By coincidence.

As `typeof(options.isForWebkit !== "undefined")` is always true, we can ignore this condition.
Thus:

```options? options.isForWebkit : this.isForWebkit```

And having `this.isForWebkit` set by default to `true`, we can simplify it to:

```options? options.isForWebkit : true```

So `isForWebkit` is `true` unless you provide an empty map as options (or a map that doesn't include `isForWebkit`). Then, you'll see the error.

Thanks for spotting that typo, I wrote a test for it as well.

You can check the fixed version here:
https://github.com/andrusieczko/clip-path-polygon/pull/18

Cheers,
Karol

**Comment by hongaar** [comment]
:+1: thanks for the quick fix!

**Comment by andrusieczko** [comment]
Ah, forgot to ask that you can get the new version (0.1.8) from either npm, bower or just download the minified file.

Thanks again,
Karol
