### ISSUE TITLE
Generated svg add empty space after all content

### ISSUE THREAD

**Issue by zoxon** [andrusieczko/clip-path-polygon#19]
http://codepen.io/Zoxon/pen/Kzrvoz

**Comment by andrusieczko** [comment]
Hey,

Thanks for raising the issue, I'll try to look at it soon!

Cheers,
Karol

**Comment by zoxon** [comment]
Try attribute `style="width:0;height:0;visibility:hidden;position:absolute;"` to svg

**Comment by andrusieczko** [comment]
Hey,

I added `display: none` to all the `svg` elements I'm creating.

I hope it'll help :)

Thanks again!

Cheers,
Karol

**Comment by zoxon** [comment]
Thank you, but with `display: none` svg path not work

**Comment by andrusieczko** [comment]
Hmm, which browser do you use? It seems to be working with your codepen (when I add `display: none` manually).

**Comment by andrusieczko** [comment]
Did you use the newest file?

https://raw.githubusercontent.com/andrusieczko/clip-path-polygon/master/build/clip-path-polygon.min.js

**Comment by zoxon** [comment]
Open this demo in firefox
http://codepen.io/Zoxon/pen/Kzrvoz
![2016-05-07_08-49-11](https://cloud.githubusercontent.com/assets/3866196/15089894/ad7c5824-1430-11e6-8c49-3ed18af0e7bb.png)

**Comment by andrusieczko** [comment]
Hey, you were right. Weirdly enough, it doesn't happen in all the cases, that's why I got confused.

Take a look at this PR: #22, let me know if it works for you, I'll merge it and npm publish it.

Thanks again!
Karol

**Comment by zoxon** [comment]
This work for me http://codepen.io/Zoxon/pen/GZzqav

```js
var $svg = this._createSvgElement('svg').attr('width', 0).attr('height', 0).css({
	'width': 0,
	'height': 0,
	'visibility': 'hidden',
	'position': 'absolute'
});
```

![2016-05-07_20-54-29](https://cloud.githubusercontent.com/assets/3866196/15092807/0c2aadf2-1496-11e6-8fef-35846b088c75.png)

I'm modify script inside my project. Test only on firefox and chrome

And better use this styles in future
```css
  border: 0 !important;
  clip: rect(0 0 0 0) !important;
  height: 1px !important;
  margin: -1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
```

**Comment by andrusieczko** [comment]
Hi,

I added
```    'width': 0,
    'height': 0,
    'visibility': 'hidden',
    'position': 'absolute'```

I'm going to merge it and publish as 0.10. 

Hopefully it works for everybody now! :)

Cheers,
Karol
