### ISSUE TITLE
Percentages in clip-path

### ISSUE THREAD

**Issue by Matttyna** [andrusieczko/clip-path-polygon#2]
Hi,
it´s great work, but - I have a responsive website, and I want use your jQuery for background. Is there some way to use percentages clip-path, please?
For example:
clip-path: polygon(50% 7%, 100% 0, 100% 93%, 50% 100%, 0 93%, 0 0); 

Thanks! :)

**Comment by andrusieczko** [comment]
Hey, I'll take a look at that (possibly this week, maybe today?). Thanks!

**Comment by Matttyna** [comment]
Oh, yes!
IT works, good job.

I saved your script to my ftp.
I use it with https://github.com/srobbin/jquery-backstretch - no conflict and very good combination!

Nice day!
Martina

**Comment by andrusieczko** [comment]
Hey, I'm glad it worked.

Unfortunately, I think I didn't fully understand your question though...

Don't you want to have it like that?

    $(function() {
      var points = [[50, 0], [100, 0], [100, 85], [50, 99], [0, 86],[0, 0]];
      var body = [[50, 7], [100, 0], [100, 93], [50, 100], [0, 93],[0, 0]];
      var options = {isPercentage: true};
      $('#head').clipPath(points, options);
      $('#portfolio').clipPath(body, options);
      $('#foot').clipPath(body, options);
    });

**Comment by Matttyna** [comment]
Yes, something like this, but first #head may be some other polygon than
portfolio and foot.

Please have a look on this:

My error screenshot: http://snag.gy/5VHVV.jpg

I code this .psd:
http://gdj.gdj.netdna-cdn.com/wp-content/uploads/2014/04/arrow_psd_templates.jpg

Understand you, what I want?
Thanks for reply! :-)


2015-04-01 15:11 GMT+02:00 Karol Andrusieczko <notifications@github.com>:

**Comment by andrusieczko** [comment]
I think you might want to use the option `svgDefId` to have different definitions of clippath. Is that what you're looking for?

**Comment by Matttyna** [comment]
Yes, I think, that is!
But - how, please? :-(

2015-04-01 17:31 GMT+02:00 Karol Andrusieczko <notifications@github.com>:

**Comment by andrusieczko** [comment]
Hey, please find the documentation updated here:
https://github.com/andrusieczko/clip-path-polygon

and the example:
https://raw.githubusercontent.com/andrusieczko/clip-path-polygon/master/resources/example.html

(just download the file and open in the browser).

I hope it'll help!

**Comment by Matttyna** [comment]
Yes, It´s perfect for me :).
Looking like a psd template :).

Thanks for all, and good luck.

M.
