### ISSUE TITLE
svg display: none breaking clip in FF OSX

### ISSUE THREAD

**Issue by danwild** [andrusieczko/clip-path-polygon#23]
In the l[atest commit](https://github.com/andrusieczko/clip-path-polygon/commit/1b6fd2d830de05c3590094db4825b93e734d0509),`.css('display', 'none')` on the svg elem (clip-path-polygon.js: 100) breaks the clip behaviour (by break, I mean I'm not getting any clip applied).

I'm using FF v46.0.1 on OSX.

If I use `opacity: 0` instead - clip works as expected; however I also see that this change was made to eliminate empty space created by the empty elem - which will obviously won't be addressed by opacity..

**Comment by andrusieczko** [comment]
Yes, it was pointed out to me in #19. #22 fixes the problem, I'll try to release it in a couple of hours.

I'm sorry for any inconvenience caused.

Thanks!

**Comment by andrusieczko** [comment]
Hi,

I released 0.10, please check if it works for you now.

Cheers,
Karol

**Comment by danwild** [comment]
Sorry I didn't see the PR addressing the issue - I've updated to v0.10 and it's working great - thanks again!

Cheers,
Dan
