### ISSUE TITLE
Upgrade chrome 55 breaks script

### ISSUE THREAD

**Issue by verlev** [andrusieczko/clip-path-polygon#24]
Chrome 55:
'CSS Clipping Path properties no longer require the webkit prefix.'

=> this means chrome gets the clip-path: url("#clippathid") iso clip-path: polygon(
and it doesn't work (no clip path applied)

For me changing the order in _createClipPath worked: first do the isForSvg and then isForWebkit. Still gives the -webkit- prefix which chrome strips.

Tested in the latest Chrome, FF, Opera, Safari on mac and IE11, Edge and Chrome on windows.

```javascript
_createClipPath: function(points) {
  this._createSvgDefs();
  if (this.isForSvg) {
    this._createSvgBasedClipPath(points);
  }
  if (this.isForWebkit) {
    this._createWebkitClipPath(points);
  }
},
```

**Comment by andrusieczko** [comment]
Hi @verlev,

Thank you so much for this!

I already fixed it.
The newest version (0.1.11) is available on `npm` and `bower`.

Thanks again!
Karol
