### ISSUE TITLE
Not supporting safari 5.1 version

### ISSUE THREAD

**Issue by amitabhaghosh197** [andrusieczko/clip-path-polygon#5]
It is great plugin. Working fine in firefox and chrome but why it is not working in safari 5.1 version. Can you please help me how to work for safari 5.1
Thanks in advance

**Comment by andrusieczko** [comment]
Hi @amitabhaghosh197,

Thanks for a good word! :)

Unfortunately, I'm not supporting the legacy browsers... It's working fine on the newest Safari as well as Safari 7 and Safari 7.1.

Moreover, all the Safari versions before Safari 7 didn't support the `clip-path` property at all. Please refer to: http://caniuse.com/#feat=css-clip-path

I should probably add the versions of browsers that I support I guess to README file, so thanks for that issue!

Regards,
Karol

**Comment by amitabhaghosh197** [comment]
Thanks for your reply. I just want to clear out my some doubts. I don't have Mac. So I have learned that some Mac OS supports Safari 5.1. Is it true? If so then is there any option of upgrade of Safari in that OS. I am referencing as per my purview of Browser Stack.

**Comment by andrusieczko** [comment]
Hi @amitabhaghosh197,

I'm using Mac now. I've got Safari 8.0.6, it's being updated automatically.

If somebody didn't upgrade one's OS from Snow Leopard (v10.6, latest version from Sep 2013, now I'm using v10.10.3), then I guess chances are one have Safari v5.1 installed. But still, it is not officially supported anymore even by Apple, so this person shouldn't be surprised that some pages are not rendered correctly.

Moreover, unlike all the Windows OS's before Windows 10 (presumably), you can upgrade (and you are encouraged to do so) you MacOS for free . Just download and install. And it works. Same thing with Safari.

The latest supported version right now is v6.2.

Regards,
Karol
