### ISSUE TITLE
2 polygon in the same page

### ISSUE THREAD

**Issue by j4rk0r** [andrusieczko/clip-path-polygon#6]
Hi, thanks for your script it´s cool!

But i have a problem, when i use the script to generate 2 mask in the same page not work!
Any idea or solution for that?

Thanks!

**Comment by andrusieczko** [comment]
Hi @j4rk0r,

Thanks for using my lib :)

I'll take a look at your issue later today.

Thanks,
Karol

**Comment by j4rk0r** [comment]
Thanks i´m wait that.

Thanks

**Comment by andrusieczko** [comment]
Hey again,

Can you please send me an example how you use it?

I just saw that even in the [example.html](https://github.com/andrusieczko/clip-path-polygon/blob/master/resources/example.html) file that it works with multiple elements.

Your code would be helpful with resolving this issue.

Thanks,
Karol

**Comment by andrusieczko** [comment]
`svgDefId` is not mandatory in Firefox anymore.

Please check the newest version (`0.1.6`) or download (clip-path-polygon.min.js)[https://raw.githubusercontent.com/andrusieczko/clip-path-polygon/master/build/clip-path-polygon.min.js].

Cheers,
Karol

**Comment by j4rk0r** [comment]
It´s great!!! thanks but now i have other problem, i go to open a new issue, if you can help me im very happy!!! thanks
