### ISSUE TITLE
The size of mask-of

### ISSUE THREAD

**Issue by j4rk0r** [andrusieczko/clip-path-polygon#8]
hi my friend, now i use your script to make an editor of pics to decoration, the user enter in a site, select her image and it´s put in a mask an her can see a preview of her pic...

The problem:
When user select a pic, and this is more big than mask, the elements in the page is move to border or image that is the mask, you can try in the next link:
http://curvart.creacionwebprofesional.com/personalizar/curvart-plano/204

1) Push in right to: "Imagen principal > Subir" 
2) When you up yout image, the button without absolute position is move to border of image. You can see that with the checkbox: "Ajustar imagen"

Can you help me with that please?

**Comment by andrusieczko** [comment]
Hey @j4rk0r,

I'm not sure if I understood your problem, you're probably not cutting the image at all or...

Anyway, I guess there's no problem with the library itself, right?

If you have a problem how to design your website, then I recommend stackoverflow.com. If there's something wrong with the library, I'll fix it here.

If there's no issue with `clip-path-polygon` itself, I'm gonna close the issue.

**Comment by andrusieczko** [comment]
Hey again,

I looked at it and I think I understood your problem.

I think what you need to do is as follows:
1. import `clip-path-polygon`: 

```
<script src="https://cdn.rawgit.com/andrusieczko/clip-path-polygon/master/build/clip-path-polygon.min.js"></script>
```

2. put this code somewhere:

```
jQuery(".commerce-product-field").clipPath([[666,0],[55.7,0],[0,302.6],[721.7,302.6]])
```

Then you'll hopefully understand how clipping the mask works.

**Comment by andrusieczko** [comment]
Hi @j4rk0r,

Can I close this issue?

Cheers,
Karol

**Comment by andrusieczko** [comment]
Hi @j4rk0r,

As I haven't heard from you since October, I'm closing this issue.

Cheers,
Karol
