### ISSUE TITLE
Any future support for Internet Explorer or Edge browsers?

### ISSUE THREAD

**Issue by victorbadila** [andrusieczko/clip-path-polygon#9]
Like this module a lot and would really need it in the IE stack

**Comment by andrusieczko** [comment]
Hi @victorbadila,

I'm sorry for a late response, I was unavailable yesterday.

I haven't planned it to be honest as I don't own any windows machine at the moment but I can try.

Unfortunately, I won't have time until late next week to look at this issue...

Let me get back to you in a couple of days, thanks for raising the problem.

Cheers,
Karol

**Comment by victorbadila** [comment]
Sure, if you have no time don't stress it. I eventually resorted to a fallback solution for IE/Edge for the project I was doing and the client agreed with it. Cool project anyways!

**Comment by andrusieczko** [comment]
Thanks @victorbadila.

Only if I get some access to a Windows machine, I'll try to see what's causing problems there, so I'll keep this issue open.

**Comment by victorbadila** [comment]
I'll cut this short: I tried to implement it myself, seems clip-path is not supported in IE and Edge, except in some weird cases: for images inside svgs, something weird like that. Did not find any polyfill either:
http://caniuse.com/#search=clip-path

**Comment by andrusieczko** [comment]
Thanks @victorbadila,

Still, I'll have some access to Windows in December/January time, so I'll look at it once again.

I guess it'll be too late for you anyway but I'll try to do my best.

Thanks for having so much interest in the project! :)
Karol
